# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from tank.platform.qt import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(474, 142)
        self.verticalLayout_7 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.main_stack = QtGui.QStackedWidget(Dialog)
        self.main_stack.setObjectName("main_stack")
        self.main = QtGui.QWidget()
        self.main.setObjectName("main")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.main)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.ui1_button_2 = QtGui.QToolButton(self.main)
        self.ui1_button_2.setMinimumSize(QtCore.QSize(160, 85))
        self.ui1_button_2.setMaximumSize(QtCore.QSize(150, 85))
        self.ui1_button_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ui1_button_2.setIconSize(QtCore.QSize(32, 32))
        self.ui1_button_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.ui1_button_2.setObjectName("ui1_button_2")
        self.horizontalLayout_8.addWidget(self.ui1_button_2)
        self.ui2_button_2 = QtGui.QToolButton(self.main)
        self.ui2_button_2.setMinimumSize(QtCore.QSize(160, 85))
        self.ui2_button_2.setMaximumSize(QtCore.QSize(150, 85))
        self.ui2_button_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ui2_button_2.setIconSize(QtCore.QSize(32, 32))
        self.ui2_button_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.ui2_button_2.setObjectName("ui2_button_2")
        self.horizontalLayout_8.addWidget(self.ui2_button_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.main_stack.addWidget(self.main)
        self.convert = QtGui.QWidget()
        self.convert.setObjectName("convert")
        self.gridLayout = QtGui.QGridLayout(self.convert)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.line_edit = QtGui.QLabel(self.convert)
        self.line_edit.setObjectName("line_edit")
        self.horizontalLayout_2.addWidget(self.line_edit)
        self.browse_button = QtGui.QPushButton(self.convert)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.browse_button.sizePolicy().hasHeightForWidth())
        self.browse_button.setSizePolicy(sizePolicy)
        self.browse_button.setObjectName("browse_button")
        self.horizontalLayout_2.addWidget(self.browse_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.combo_box = QtGui.QComboBox(self.convert)
        self.combo_box.setObjectName("combo_box")
        self.verticalLayout_2.addWidget(self.combo_box)
        self.label = QtGui.QLabel(self.convert)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ok_button = QtGui.QPushButton(self.convert)
        self.ok_button.setObjectName("ok_button")
        self.horizontalLayout_4.addWidget(self.ok_button)
        self.cancel_button = QtGui.QPushButton(self.convert)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_4.addWidget(self.cancel_button)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.main_stack.addWidget(self.convert)
        self.create_excel = QtGui.QWidget()
        self.create_excel.setObjectName("create_excel")
        self.gridLayout_3 = QtGui.QGridLayout(self.create_excel)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.line_dir_path = QtGui.QLineEdit(self.create_excel)
        self.line_dir_path.setObjectName("line_dir_path")
        self.horizontalLayout_5.addWidget(self.line_dir_path)
        self.btn_browse = QtGui.QPushButton(self.create_excel)
        self.btn_browse.setObjectName("btn_browse")
        self.horizontalLayout_5.addWidget(self.btn_browse)
        self.btn_clear = QtGui.QPushButton(self.create_excel)
        self.btn_clear.setObjectName("btn_clear")
        self.horizontalLayout_5.addWidget(self.btn_clear)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.label_save_path = QtGui.QLabel(self.create_excel)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_save_path.sizePolicy().hasHeightForWidth())
        self.label_save_path.setSizePolicy(sizePolicy)
        self.label_save_path.setObjectName("label_save_path")
        self.verticalLayout_6.addWidget(self.label_save_path)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn_create = QtGui.QPushButton(self.create_excel)
        self.btn_create.setObjectName("btn_create")
        self.horizontalLayout_7.addWidget(self.btn_create)
        self.btn_cancel = QtGui.QPushButton(self.create_excel)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_7.addWidget(self.btn_cancel)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 0, 1, 1, 1)
        self.main_stack.addWidget(self.create_excel)
        self.verticalLayout_7.addWidget(self.main_stack)

        self.retranslateUi(Dialog)
        self.main_stack.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "ShotGrid Publish", None, QtGui.QApplication.UnicodeUTF8))
        Dialog.setAccessibleName(QtGui.QApplication.translate("Dialog", "publish dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.main_stack.setAccessibleName(QtGui.QApplication.translate("Dialog", "stackedwidget", None, QtGui.QApplication.UnicodeUTF8))
        self.ui1_button_2.setToolTip(QtGui.QApplication.translate("Dialog", "Browse files to publish", None, QtGui.QApplication.UnicodeUTF8))
        self.ui1_button_2.setText(QtGui.QApplication.translate("Dialog", "Create Excel File", None, QtGui.QApplication.UnicodeUTF8))
        self.ui2_button_2.setToolTip(QtGui.QApplication.translate("Dialog", "Browse sequences to publish", None, QtGui.QApplication.UnicodeUTF8))
        self.ui2_button_2.setText(QtGui.QApplication.translate("Dialog", "Convert and Upload", None, QtGui.QApplication.UnicodeUTF8))
        self.line_edit.setText(QtGui.QApplication.translate("Dialog", "Path :", None, QtGui.QApplication.UnicodeUTF8))
        self.browse_button.setText(QtGui.QApplication.translate("Dialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Converting Project:", None, QtGui.QApplication.UnicodeUTF8))
        self.ok_button.setText(QtGui.QApplication.translate("Dialog", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_button.setText(QtGui.QApplication.translate("Dialog", "CANCEL", None, QtGui.QApplication.UnicodeUTF8))
        self.create_excel.setAccessibleName(QtGui.QApplication.translate("Dialog", "Main publish frame", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_browse.setText(QtGui.QApplication.translate("Dialog", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_clear.setText(QtGui.QApplication.translate("Dialog", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.label_save_path.setText(QtGui.QApplication.translate("Dialog", "Save Directory", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_create.setText(QtGui.QApplication.translate("Dialog", "Create", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_cancel.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

from . import resources_rc
